### PR TITLE
Javascript files should add application/javascript in response header…

### PR DESCRIPTION
**Pull request by xiexiao**
Javascript files should add application/javascript in response header in Chrome.

### CODE REVIEW

**Comment by pgaskin** [comment]
The embedded JS files are *already* [served](https://github.com/golang/go/blob/master/src/net/http/fs.go#L235) with the correct response header. Also, this would be the wrong place to add the header if it wasn't.

Thanks anyways!

**Comment by xiexiao** [comment]
Hey, I look into the code details.
https://github.com/golang/go/blob/master/src/mime/type.go#L105
// On Windows, MIME types are extracted from the registry.

I run easy-novnc on Windows 10.
And in the registry, the .js file set the Content Type is `text/plain`.

**Comment by pgaskin** [comment]
Some application must have done it since I can't reproduce it on my VM (the registry doesn't override the mimetype for `.js`).

**Comment by xiexiao** [comment]
I just fixed the problem by change the Content Type from text/plain to text/javascript of .js in the registry.
Every thing is ok now.
Thanks!

**Pull request closed without merging**
